# Generated by Django 2.2.7 on 2019-12-10 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bets_history',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Played_Matches'),
        ),
    ]
