# Generated by Django 2.2.7 on 2019-12-08 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.DecimalField(blank=True, decimal_places=2, default='', max_digits=10)),
                ('card_name', models.CharField(blank=True, default='', max_length=30)),
                ('card_number', models.IntegerField(blank=True, default='')),
                ('exp_date', models.CharField(blank=True, default='', max_length=30)),
                ('cvv', models.IntegerField(blank=True, default='')),
                ('payment_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
