# Generated by Django 2.2.7 on 2019-12-08 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20191209_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='money',
            new_name='balance',
        ),
    ]
