# Generated by Django 2.2.7 on 2019-12-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20191209_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='bets',
            name='possible_win',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
