# Generated by Django 2.2.7 on 2019-12-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20191209_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='game_end',
            field=models.DateTimeField(default='2019-01-01'),
            preserve_default=False,
        ),
    ]
