# Generated by Django 2.2.7 on 2019-12-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_matches_game_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='game_end',
            field=models.DateTimeField(blank=True),
        ),
    ]
