# Generated by Django 2.2.7 on 2019-12-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20191209_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='status',
            field=models.CharField(choices=[('CP', 'CP'), ('GO', 'GO'), ('EX', 'EX')], default='EX', max_length=2),
        ),
    ]
