# Generated by Django 2.2.7 on 2019-12-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_auto_20191209_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('GOING', 'GOING'), ('EXPECTED', 'EXPECTED')], default='EXPECTED', max_length=10),
        ),
    ]
