# Generated by Django 2.2.7 on 2019-12-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_auto_20191209_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='available',
        ),
        migrations.AddField(
            model_name='bets',
            name='winner',
            field=models.CharField(default='Unknown', max_length=5),
        ),
        migrations.AddField(
            model_name='matches',
            name='winner',
            field=models.CharField(choices=[('WIN1', 'WIN1'), ('WIN2', 'WIN2'), ('DRAW', 'DRAW')], default='Unknown', max_length=5),
        ),
    ]
